### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mixxamm**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mixxamm Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-accessing-mongodb-data-rest&pullRequestId=21)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-accessing-mongodb-data-rest&pullRequestId=21) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by mixxamm** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@mixxamm This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by Buzzardo** [comment]
Yes, it was. Thanks. :)

**Pull request merged**
